[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SITE_NAME = "forgepage"
  NEXT_PUBLIC_ASSET_BASE = "/"


